### ISSUE TITLE
Objeto 3D

### ISSUE THREAD

**Issue by Gregorio012** [SistemasTecTlaxiaco/actividad-4-diseno-de-objeto-3d-en-blender-equipo-gregorio-8us#1]
[Objeto3D.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-diseno-de-objeto-3d-en-blender-equipo-gregorio-8us/files/14655628/Objeto3D.pdf)

**Comment by salathiel1999** [comment]
20%

**Comment by josealfredo79** [comment]
Bien echo y revisado...
